### ISSUE TITLE
nginxproxymanager icon does not work

### ISSUE THREAD

**Issue by iwa** [Zareix/dashed#5]
for some reason, the `nginxproxymanager.png` from [dashboard-icons](https://github.com/walkxhub/dashboard-icons/tree/master/svg) does not work :
![Screen Shot 2022-07-14 at 20 27 05](https://user-images.githubusercontent.com/19956672/179055914-6bbde5ca-d0ac-4ed3-ab2e-fe4f85fe7680.png)

in my config:
```json
"categories": [
        {
            "name": "Server",
            "icon": "MdWbCloudy",
            "apps": [
                {
                    "name": "Portainer",
                    "url": "https://dedie:9443/",
                    "image": "portainer.svg"
                },
                {
                    "name": "NPM",
                    "url": "http://dedie:81/",
                    "image": "nginxproxymanager.png"
                },
                {
                    "name": "Duplicati",
                    "url": "http://dedie:8200/ngax/index.html",
                    "image": "duplicati.png"
                }
            ]
        }
...
```

maybe it could be better if we can input direct links to images?

**Comment by iwa** [comment]
or could it fetch the favicon, and "image" could override it with any link we put in it?

**Comment by Zareix** [comment]
Images are resolved like so :
- Check if the image field is set and point to an image in the public/assets folder
- If none : we use [walkxhub/dashboard-icons](https://github.com/walkxhub/dashboard-icons) :
         - get the app name
         - toLowerCase()
         - replace spaces with dash ("-")
- if still none
- replace with default icon

**Comment by iwa** [comment]
trying to fetch the favicon in the process could be a great addition i think, most modern websites nowadays provide a high-quality favicon so it could be worth the shot

**Comment by Zareix** [comment]
Noted :)
